### ISSUE TITLE
how to resize AppBar on some event

### ISSUE THREAD

**Issue by Enghouse-CCSP-PS** [mgaffigan/WpfAppBar#5] opened 2023-08-06 08:06 UTC
What is best approach to make appBar to be extended for full screen and then moved to original docked size?
The logic behind is that user can trigger application to take full screen , work in full screen and then turn app back to AppBar when no need to full screen?

**Comment by mgaffigan** [comment] 2023-08-14 21:57
This sounds like a duplicate of [#3 Undock after a window has been docked](https://github.com/mgaffigan/WpfAppBar/issues/3).  A sample of a window which can be docked and undocked is available at [UndockSample](https://github.com/mgaffigan/WpfAppBar/tree/master/UndockSample).

I'm going to close, but if the above does not address the question, please clarify and reopen.

**Closed by mgaffigan** 2023-08-14 21:57 UTC
Labels: duplicate
